const express = require('express');
const serveIndex = require('serve-index');
const path = require('path');
const fs = require('fs');
const app = express();

function isDirectoryValid(directoryPath) {
  try {
    const stats = fs.statSync(directoryPath);
    return stats.isDirectory();
  } catch (error) {
    return false;
  }
}

const BASE_DIR = process.env.BASE_DIR || path.join(__dirname, 'static');
console.log(BASE_DIR);
if(isDirectoryValid(BASE_DIR)){
  const PORT = 8000;
  app.use(express.static(BASE_DIR));

  // Enable directory listings
  app.use('/', serveIndex(BASE_DIR, {'icons': true}));

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`nodejs is running at port: ${PORT}`);
  });
}

// wget -r -np -nH -N -R "index.html*" http://192.168.169.224:8000/
/*
- `-r`: Recursive download.
- `-np`: Do not follow links to parent directories (avoids going up the directory tree).
- `-nH`: Disable generation of host-prefixed directories.
- `--cut-dirs=1`: Ignore the first directory (files) in the URL path. Adjust the number if your URL structure is different.
- `--reject "index.html"`: Do not download `index.html` files (which are generated by Flask for directory listings).
*/