@echo off
chcp 65001

echo 请输入/拖入文件夹（默认为./static）
set /p "BASE_DIR=>>> "
for %%i in ("%BASE_DIR%") do set "FOLDER_NAME=%%~nxi"

setlocal enabledelayedexpansion
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"IPv4 Address"') do (
    set "ip=%%a"
    set "ip=!ip:~1!"
    echo !ip!
)

echo.
echo 文件服务启动中，下载请使用以下命令
echo $ wget -r -q -np -nH -N -R "index.html*" http://%ip%:8000/ -P %FOLDER_NAME%
endlocal

echo.
echo  "-r 递归下载服务器路径下的文件"
echo  "-q 不打印日志"
echo  "-np 不访问 base url 之前的内容"
echo  "-nH 不使用域名和端口来命名保存文件夹"
echo  "--progress=bar:force 强制显示进度条"
echo  "-P /path/to/dir 指定下载内容保存路径"
echo  "-R 'index.html*' 不保存符合pattern的文件"
echo.
echo =====================

node app.js

pause

:: -r: recuisive, 
:: -np: don't visit url beyond baseURL
:: -nH: don't use host-prefixed dir
:: --cut-dirs=1: Ignore the first directory (files) in the URL path. Adjust the number if your URL structure is different.
:: --reject "index.html": Do not download `index.html` files (which are generated by Flask for directory listings).
